Added table syntax
malivinayak/Markdown pull request #5
Opened 2022-10-15 13:30 UTC by adilJamshad

2022-10-15 13:34 UTC, malivinayak commented
@adilJamshad 

To add a syntax which can visible in markup code you have to use triple back tick sign i.e. ``` 

e.g.
```
| Sr  | Name |
| --- | ---- |
| 0   | Adil |
```

2022-10-15 13:35 UTC, malivinayak requested changes
add ``` triple back tick so that others can see markup code directly

2022-10-15 13:35 UTC, malivinayak commented on README.md
> +
add ``` here

2022-10-15 13:35 UTC, malivinayak commented on README.md
> +| 0   | Adil |
add ``` here below this line

2022-10-15 13:36 UTC, malivinayak commented
Thank You for your contribution @adilJamshad 
Just make that two small changes and I will merge your PR

2022-10-15 13:39 UTC, malivinayak commented
@adilJamshad just comment in #3 so that I can assign your for that issue

2022-10-15 14:28 UTC, malivinayak commented
Refer #7  To make PR

2022-10-15 15:22 UTC, adilJamshad commented on README.md
> +| 0   | Adil |
I have added ``` here

2022-10-15 15:22 UTC, adilJamshad commented on README.md
> +
I have added ``` here

2022-10-16 03:23 UTC, malivinayak commented
In order to make it more user friendly you have to follow this structure
![image](https://user-images.githubusercontent.com/66154908/196016418-70c6838a-4fd3-40fe-865b-2c5fb910d7bf.png)

2023-03-26 08:16 UTC, closed without merging